### j'importe le dataframe final du bodacc

In [9]:
import pandas as pd
from datetime import datetime, timedelta 
from keplergl import KeplerGl

In [35]:
df = pd.read_csv('data.csv')
df2 = df[(df.activite_déclarée != "non renseigné")]
df2

,Unnamed: 0,siren,departement,date_publication,activite_déclarée,code_ape,activte_insee
0,0,392749974,01,2020-01-14,"comptabilité, gestion des entreprises",69.20Z,Activités comptables
1,1,880121256,01,2020-01-14,débit de tabac - journaux - papeterie - bimbel...,47.11B,Commerce d'alimentation générale
2,2,880461090,01,2020-01-14,vente de contenu informatique.,47.91B,Vente à distance sur catalogue spécialisé
3,3,488404450,01,2020-01-14,"presse, papeterie, jeux fdj, bimbeloterie, lib...",56.30Z,Débits de boissons
4,4,877997445,01,2020-01-14,site e-commerce : vente en ligne de chocolats,47.91B,Vente à distance sur catalogue spécialisé
...,...,...,...,...,...,...,...
57508,57508,845191253,973,2020-01-12,Profession d'avocat,69.10Z,Activités juridiques
57509,57509,849961032,974,2020-01-12,"Snack, plats à emporter",56.10C,Restauration de type rapide
57510,57510,880240924,974,2020-01-12,"Exploitation de restaurant, pub, bar, discothè...",56.10A,Restauration traditionnelle
57511,57511,528447212,974,2020-01-12,"Acquisition, administration, exploitation par ...",68.20B,Location de terrains et d'autres biens immobil...
57512,57512,848597647,974,2020-01-12,L'achat et la gestion de centre de remise en f...,93.13Z,Activités des centres de culture physique

In [37]:
df3 = df2[(df2.activite_déclarée != "aucune activite")]
df3.drop['Unnamed:0']

TypeError: 'method' object is not subscriptable

In [23]:
df_activite= df3[(df3.code_ape != "APE Non Diffusable")]
df_activite

,Unnamed: 0,siren,departement,date_publication,activite_déclarée,code_ape,activte_insee
0,0,392749974,01,2020-01-14,"comptabilité, gestion des entreprises",69.20Z,Activités comptables
1,1,880121256,01,2020-01-14,débit de tabac - journaux - papeterie - bimbel...,47.11B,Commerce d'alimentation générale
2,2,880461090,01,2020-01-14,vente de contenu informatique.,47.91B,Vente à distance sur catalogue spécialisé
3,3,488404450,01,2020-01-14,"presse, papeterie, jeux fdj, bimbeloterie, lib...",56.30Z,Débits de boissons
4,4,877997445,01,2020-01-14,site e-commerce : vente en ligne de chocolats,47.91B,Vente à distance sur catalogue spécialisé
...,...,...,...,...,...,...,...
57508,57508,845191253,973,2020-01-12,Profession d'avocat,69.10Z,Activités juridiques
57509,57509,849961032,974,2020-01-12,"Snack, plats à emporter",56.10C,Restauration de type rapide
57510,57510,880240924,974,2020-01-12,"Exploitation de restaurant, pub, bar, discothè...",56.10A,Restauration traditionnelle
57511,57511,528447212,974,2020-01-12,"Acquisition, administration, exploitation par ...",68.20B,Location de terrains et d'autres biens immobil...
57512,57512,848597647,974,2020-01-12,L'achat et la gestion de centre de remise en f...,93.13Z,Activités des centres de culture physique

### je rajoute les heures et les minutes

In [24]:
# rajouter les heures et les minutes
test = ' 0:00'
df['date_publication'] = df['date_publication'] + test
df

,Unnamed: 0,siren,departement,date_publication,activite_déclarée,code_ape,activte_insee
0,0,392749974,01,2020-01-14 0:00,"comptabilité, gestion des entreprises",69.20Z,Activités comptables
1,1,880121256,01,2020-01-14 0:00,débit de tabac - journaux - papeterie - bimbel...,47.11B,Commerce d'alimentation générale
2,2,880461090,01,2020-01-14 0:00,vente de contenu informatique.,47.91B,Vente à distance sur catalogue spécialisé
3,3,488404450,01,2020-01-14 0:00,"presse, papeterie, jeux fdj, bimbeloterie, lib...",56.30Z,Débits de boissons
4,4,877997445,01,2020-01-14 0:00,site e-commerce : vente en ligne de chocolats,47.91B,Vente à distance sur catalogue spécialisé
...,...,...,...,...,...,...,...
57508,57508,845191253,973,2020-01-12 0:00,Profession d'avocat,69.10Z,Activités juridiques
57509,57509,849961032,974,2020-01-12 0:00,"Snack, plats à emporter",56.10C,Restauration de type rapide
57510,57510,880240924,974,2020-01-12 0:00,"Exploitation de restaurant, pub, bar, discothè...",56.10A,Restauration traditionnelle
57511,57511,528447212,974,2020-01-12 0:00,"Acquisition, administration, exploitation par ...",68.20B,Location de terrains et d'autres biens immobil...
57512,57512,848597647,974,2020-01-12 0:00,L'achat et la gestion de centre de remise en f...,93.13Z,Activités des centres de culture physique

### je recupere le dataframe avec lat et long

In [26]:
df11 = pd.read_csv('Bodacc_p.csv', sep=";")
df11
df11=df11[['Code du Département','geo_point_2d']]

lat=[]
long=[]
for e in df11['geo_point_2d']:
    e=e.split(',')
    lat.append(float(e[0]))
    long.append(float(e[1]))

df11['lat']=lat
df11['long']=long


df11['lat'].round(6)
df11['long'].round(6)

df11 = df11.drop('geo_point_2d',axis=1)
df11 = df11.drop_duplicates()
#df2

### j'attribue le meme nom de colonne "departement" aux 2 dataframes

In [28]:
df10 = df10.rename(columns={"Code du Département": "departement"})
df10

,Unnamed: 0,siren,departement,date_publication,activite_déclarée,code_ape,activte_insee
0,0,392749974,01,2020-01-14,"comptabilité, gestion des entreprises",69.20Z,Activités comptables
1,1,880121256,01,2020-01-14,débit de tabac - journaux - papeterie - bimbel...,47.11B,Commerce d'alimentation générale
2,2,880461090,01,2020-01-14,vente de contenu informatique.,47.91B,Vente à distance sur catalogue spécialisé
3,3,488404450,01,2020-01-14,"presse, papeterie, jeux fdj, bimbeloterie, lib...",56.30Z,Débits de boissons
4,4,877997445,01,2020-01-14,site e-commerce : vente en ligne de chocolats,47.91B,Vente à distance sur catalogue spécialisé
...,...,...,...,...,...,...,...
57508,57508,845191253,973,2020-01-12,Profession d'avocat,69.10Z,Activités juridiques
57509,57509,849961032,974,2020-01-12,"Snack, plats à emporter",56.10C,Restauration de type rapide
57510,57510,880240924,974,2020-01-12,"Exploitation de restaurant, pub, bar, discothè...",56.10A,Restauration traditionnelle
57511,57511,528447212,974,2020-01-12,"Acquisition, administration, exploitation par ...",68.20B,Location de terrains et d'autres biens immobil...
57512,57512,848597647,974,2020-01-12,L'achat et la gestion de centre de remise en f...,93.13Z,Activités des centres de culture physique

### je join les 2 dataframe avec la key 'departement' en commun

In [29]:
df4 = df.join(df10.set_index('departement'), on='departement')
df4

ValueError: columns overlap but no suffix specified: Index(['Unnamed: 0', 'siren', 'date_publication', 'activite_déclarée',
       'code_ape', 'activte_insee'],
      dtype='object')

### je suprime le 2 eme index inutile

In [6]:
df6 = df4.drop('Unnamed: 0', axis=1)
df7 = df6.groupby(['departement','date_publication', 'lat', 'long'])['siren'].count()
df7

departement  date_publication  lat         long
01           2020-01-02 0:00    46.099349  5.349928     12
             2020-01-03 0:00    46.099349  5.349928     11
             2020-01-05 0:00    46.099349  5.349928     10
             2020-01-07 0:00    46.099349  5.349928      5
             2020-01-08 0:00    46.099349  5.349928      7
                                                        ..
974          2020-02-09 0:00   -21.133204  55.532509     4
             2020-02-11 0:00   -21.133204  55.532509    16
             2020-02-12 0:00   -21.133204  55.532509     7
976          2020-01-02 0:00   -12.820613  45.147442    67
             2020-02-04 0:00   -12.820613  45.147442    62
Name: siren, Length: 1798, dtype: int64

### j'affiche mes données sur une carte kepler

### je rajoute une colonne qui compte le nombre de d'activités

In [7]:
#df6 = df5.groupby(['lat','long']).size()
#df6
df5['counts'] = df5['departement'].map(df5['departement'].value_counts())
df5

NameError: name 'df5' is not defined

In [ ]:
map_3 = KeplerGl(height=500)
map_3.add_data(data=df6, name='data')
map_3

In [ ]:
df5.groupby(by=["departement"], dropna=False).count()

#df4 = df5.groupby(['departement','lat','long'])['siren'].count()
#df4 = pd.DataFrame(df4)
#df4.reset_index(inplace=True)
#df4

In [ ]:
df4.columns

In [ ]:
map_4 = KeplerGl(height=500)
map_4.add_data(data=df4, name='data')